### ISSUE TITLE
Problem when using extract

### ISSUE THREAD

**Issue by altaetran** [gem-pasteur/macsyfinder#19]
Hi, I am trying to run macsyfinder, but I find the following error:

```
Exception in thread Thread-12:
Traceback (most recent call last):
  File "/broad/software/free/Linux/redhat_6_x86_64/pkgs/python_2.7.1-sqlite3-rtrees/lib/python2.7/threading.py", line 530, in __bootstrap_inner
    self.run()
  File "/broad/software/free/Linux/redhat_6_x86_64/pkgs/python_2.7.1-sqlite3-rtrees/lib/python2.7/threading.py", line 483, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/broad/zhanglabdata/Han/packages/Macsyfinder/macsypy/lib/python2.7/site-packages/macsypy/search_genes.py", line 71, in search
    report.extract()
  File "/broad/zhanglabdata/Han/packages/Macsyfinder/macsypy/lib/python2.7/site-packages/macsypy/report.py", line 297, in extract
    seq_lg, position_hit = my_db[hit_id]
TypeError: 'NoneType' object is not iterable

```

The installation tests worked correctly, but it doesn't seem to be able to work on an example, and I'm not sure what test data I can try it on besides my own. Thanks!

**Comment by altaetran** [comment]
Seems related to file location? Seems like naming the input 'tmp_in.fa' or 'test_in.fa' produces this bug, while simply naming 'tmp.fa' or 'test.fa' doesn't do this... Very strange... Can someone comment on why this might be the case?

**Comment by altaetran** [comment]
However, I'm still getting bugs regarding this issue even with different datasets

**Comment by altaetran** [comment]
Ok, I found out that the problem is that macsyfinder doesn't automatically reindex if the input file contents is changed because it assumes that the input will never be changed.
