### ISSUE TITLE
Incompatibility with BLAST+ 2.10.0

### ISSUE THREAD

**Issue by ilnamkang** [gem-pasteur/macsyfinder#30]
Hi,

macsyfinder seems to be incompatible with BLAST+ 2.10.0, while it has no problem with BLAST+ 2.9.0.

This incompatibility with BLAST+ 2.10.0 may be related to the changes in BLAST database version introduced in BLAST+ 2.10.0.
(https://www.ncbi.nlm.nih.gov/books/NBK131777/)

When BLAST+ 2.10.0 is on my PATH, "python setup.py test -vv" fails with the following error messages.

======================================================================
ERROR: test_build_force (test_Indexes.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/Programs/macsyfinder-1.0.5/tests/unit/test_Indexes.py", line 208, in test_build_force
    idx.build(force=True)
  File "build/lib.linux-x86_64-2.7/macsypy/database.py", line 119, in build
    self._hmmer_indexes = self.find_hmmer_indexes()
  File "build/lib.linux-x86_64-2.7/macsypy/database.py", line 142, in find_hmmer_indexes
    raise RuntimeError(msg)
RuntimeError: some index files are missing. Delete all index files (*.phr, *.pin, *.psd, *.psi, *.psq, *.pal) and try to rebuild them.

======================================================================
ERROR: test_build_no_idx (test_Indexes.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/Programs/macsyfinder-1.0.5/tests/unit/test_Indexes.py", line 173, in test_build_no_idx
    idx.build()
  File "build/lib.linux-x86_64-2.7/macsypy/database.py", line 119, in build
    self._hmmer_indexes = self.find_hmmer_indexes()
  File "build/lib.linux-x86_64-2.7/macsypy/database.py", line 142, in find_hmmer_indexes
    raise RuntimeError(msg)
RuntimeError: some index files are missing. Delete all index files (*.phr, *.pin, *.psd, *.psi, *.psq, *.pal) and try to rebuild them.

----------------------------------------------------------------------

**Comment by bneron** [comment]
Hi  ilnamkang,

Thank's to warn us about this problem.
But we are developing a new version of macsyfinder which do not need blast any more.
I hope to release it very soon.

Bertrand
