### ISSUE TITLE
I can't install macsyfinder(v2.0rcl) sucessfully.

### ISSUE THREAD

**Issue by lkj66666** [gem-pasteur/macsyfinder#36]
Hi, thanks for you help some time ago. Recently, I have some problem when i install macsyfinder(v2.0rcl).

My installation steps are as follows：
1. I used conda to create a new environment named “macsyfinder2.0”. 
```
conda create -n macsyfinder2.0 python==3.7
conda install hmmer==3.3
``` 
2. dowload and install as user guide
```
git clone https://github.com/gem-pasteur/macsyfinder.git
cd macsyfinder
pip3 install .
```
**but it failed and show as follows:**
```
Processing /home/lkj666/software/macsyfinder-2.0rc1
  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
Collecting colorlog
  Using cached colorlog-5.0.1-py2.py3-none-any.whl (10 kB)
Collecting pyyaml
  Using cached PyYAML-5.4.1-cp37-cp37m-manylinux1_x86_64.whl (636 kB)
Collecting packaging
  Using cached packaging-21.0-py3-none-any.whl (40 kB)
Collecting networkx
  Using cached networkx-2.5.1-py3-none-any.whl (1.6 MB)
Collecting decorator<5,>=4.3
  Using cached decorator-4.4.2-py2.py3-none-any.whl (9.2 kB)
Collecting pyparsing>=2.0.2
  Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Building wheels for collected packages: macsyfinder
  Building wheel for macsyfinder (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/lkj666/miniconda3/envs/macsyfinder2.0/bin/python3.7 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-3c29h6q0/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-3c29h6q0/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-p604fw8t
       cwd: /tmp/pip-req-build-3c29h6q0/
  Complete output (69 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/macsypy
  copying macsypy/error.py -> build/lib/macsypy
  copying macsypy/package.py -> build/lib/macsypy
......................
copying macsypy/scripts/macsyfinder.py -> build/lib/macsypy/scripts
  installing to build/bdist.linux-x86_64/wheel
  running install
  running install_lib
  Traceback (most recent call last):
    File "/tmp/pip-req-build-3c29h6q0/setup.py", line 114, in get_install_data_dir
      from pip.locations import distutils_scheme
  ModuleNotFoundError: No module named 'pip.locations'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-req-build-3c29h6q0/setup.py", line 277, in <module>
      distclass=UsageDistribution
    File "/home/lkj666/miniconda3/envs/macsyfinder2.0/lib/python3.7/site-packages/setuptools/__init__.py", line 163, in setup
      return distutils.core.setup(**attrs)
    File "/home/lkj666/miniconda3/envs/macsyfinder2.0/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/lkj666/miniconda3/envs/macsyfinder2.0/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/home/lkj666/miniconda3/envs/macsyfinder2.0/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/lkj666/miniconda3/envs/macsyfinder2.0/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 335, in run
      self.run_command('install')
    File "/home/lkj666/miniconda3/envs/macsyfinder2.0/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/lkj666/miniconda3/envs/macsyfinder2.0/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/lkj666/miniconda3/envs/macsyfinder2.0/lib/python3.7/site-packages/setuptools/command/install.py", line 61, in run
      return orig.install.run(self)
    File "/home/lkj666/miniconda3/envs/macsyfinder2.0/lib/python3.7/distutils/command/install.py", line 557, in run
      self.run_command(cmd_name)
    File "/home/lkj666/miniconda3/envs/macsyfinder2.0/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/lkj666/miniconda3/envs/macsyfinder2.0/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-req-build-3c29h6q0/setup.py", line 67, in run
      subst_file(_file, {'MACSYDATA': os.path.join(get_install_data_dir(inst), 'macsyfinder'),
    File "/tmp/pip-req-build-3c29h6q0/setup.py", line 120, in get_install_data_dir
      from pip._internal.locations import distutils_scheme
  ImportError: cannot import name 'distutils_scheme' from 'pip._internal.locations' (/home/lkj666/miniconda3/envs/macsyfinder2.0/lib/python3.7/site-packages/pip/_internal/locations/__init__.py)
  ----------------------------------------
  ERROR: Failed building wheel for macsyfinder
......................
 Running setup.py clean for macsyfinder
Failed to build macsyfinder
Installing collected packages: pyparsing, decorator, pyyaml, packaging, networkx, colorlog, macsyfinder
    Running setup.py install for macsyfinder ... error
    ERROR: Command errored out with exit status 1:
     command: /home/lkj666/miniconda3/envs/macsyfinder2.0/bin/python3.7 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-3c29h6q0/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-3c29h6q0/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-_4wc9er0/install-record.txt --single-version-externally-managed --compile --install-headers /home/lkj666/miniconda3/envs/macsyfinder2.0/include/python3.7m/macsyfinder
         cwd: /tmp/pip-req-build-3c29h6q0/
    Complete output (61 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/macsypy
    copying macsypy/error.py -> build/lib/macsypy
    copying macsypy/package.py -> build/lib/macsypy
    copying macsypy/solution.py -> build/lib/macsypy
    copying macsypy/utils.py -> build/lib/macsypy
.....................................
.....................................
...................................
 Traceback (most recent call last):
      File "/tmp/pip-req-build-3c29h6q0/setup.py", line 114, in get_install_data_dir
        from pip.locations import distutils_scheme
    ModuleNotFoundError: No module named 'pip.locations'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-3c29h6q0/setup.py", line 277, in <module>
        distclass=UsageDistribution
      File "/home/lkj666/miniconda3/envs/macsyfinder2.0/lib/python3.7/site-packages/setuptools/__init__.py", line 163, in setup
        return distutils.core.setup(**attrs)
      File "/home/lkj666/miniconda3/envs/macsyfinder2.0/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/lkj666/miniconda3/envs/macsyfinder2.0/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/home/lkj666/miniconda3/envs/macsyfinder2.0/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/lkj666/miniconda3/envs/macsyfinder2.0/lib/python3.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/home/lkj666/miniconda3/envs/macsyfinder2.0/lib/python3.7/distutils/command/install.py", line 557, in run
        self.run_command(cmd_name)
      File "/home/lkj666/miniconda3/envs/macsyfinder2.0/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/lkj666/miniconda3/envs/macsyfinder2.0/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-req-build-3c29h6q0/setup.py", line 67, in run
        subst_file(_file, {'MACSYDATA': os.path.join(get_install_data_dir(inst), 'macsyfinder'),
      File "/tmp/pip-req-build-3c29h6q0/setup.py", line 120, in get_install_data_dir
        from pip._internal.locations import distutils_scheme
    ImportError: cannot import name 'distutils_scheme' from 'pip._internal.locations' (/home/lkj666/miniconda3/envs/macsyfinder2.0/lib/python3.7/site-packages/pip/_internal/locations/__init__.py)
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/lkj666/miniconda3/envs/macsyfinder2.0/bin/python3.7 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-3c29h6q0/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-3c29h6q0/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-_4wc9er0/install-record.txt --single-version-externally-managed --compile --install-headers /home/lkj666/miniconda3/envs/macsyfinder2.0/include/python3.7m/macsyfinder Check the logs for full command output.
```

I tried many times but couldn't solve this problem, can you give me some idea?
If you can give detailed steps, I will be very grateful！！！

Thanks for your time and help.

**Comment by cschu** [comment]
I had the same issue. I cloned the git repo, removed lines 39-43, 48-185, 279-280 from the `setup.py`, then installed it into the conda environment via 

```
python setup.py bdist_wheel
pip install --force-reinstall dist/*whl
```

Not sure if that broke anything, but at least it seems to be running and generates output. I wasn't able to manage the data with `macsydata`, though.

**Comment by bneron** [comment]
what is the pip version?

**Comment by cschu** [comment]
`21.1.3` in my case

**Comment by bneron** [comment]
I have no quick fix, but you can use a workaround for now. downgrade the pip version to <=20.2.1 (which is the pip bundle with python 3.9)

**Comment by cschu** [comment]
Ok, thanks. With `conda create -n macsytest 'python>=3.7' 'pip<=20.2.1'`, I can then do a normal `pip install macsyfinder`, which is good enough for now. So how's the conda package coming? :D

**Comment by lkj66666** [comment]
> I had the same issue. I cloned the git repo, removed lines 39-43, 48-185, 279-280 from the `setup.py`, then installed it into the conda environment via
> 
> ```
> python setup.py bdist_wheel
> pip install --force-reinstall dist/*whl
> ```
> 
> Not sure if that broke anything, but at least it seems to be running and generates output. I wasn't able to manage the data with `macsydata`, though.

thank you for your suggestions and answers,  Since I have some personal matters, I did not reply to you in time. I just solved the problem, based on your suggestions. Thank you again

**Comment by lkj66666** [comment]
> what is the pip version?

Thank you for your suggestion, because I have some personal matters and I haven't been able to reply you in time. I just lowered the pip version to 20.0.2 and successfully solved the problem. Thank you agian

**Comment by YiyanYang0728** [comment]
> Ok, thanks. With `conda create -n macsytest 'python>=3.7' 'pip<=20.2.1'`, I can then do a normal `pip install macsyfinder`, which is good enough for now. So how's the conda package coming? :D

This solves my problem. Many thanks.
