### ISSUE TITLE
crash when no mandatory/accessory/neutral genes are found

### ISSUE THREAD

**Issue by cschu** [gem-pasteur/macsyfinder#39]
## Version of MacsyFinder:

20211005.dev (7b73a52)

### OS

- [x] Linux
- [ ] Windows
- [ ] Mac

## Expected behavior

Don't crash.

## Actual behavior

Crash:
no `mandatory_genes`, no `accessory_genes`, no `neutral_genes` -> `self.allowed_hits` is empty -> accessing `self.allowed_hits[0]` causes an `IndexError`

## Steps to reproduce behavior

Called with

`macsyfinder -vvv -w 8 --models TXSS all --models-dir /path/to/models -o /path/to/output --db-type unordered --multi-loci all --sequence-db /path/to/fasta`

Input is a prodigal-generated proteins fasta (other prodigal-generated protein sets run fine). 

Example [proteins.faa.gz](https://github.com/gem-pasteur/macsyfinder/files/7285250/proteins.faa.gz) is attached to the issue (gzipped proteins from prodigal annotation on this genome: https://www.ncbi.nlm.nih.gov/biosample/SAMN03860328/; parameters `    prodigal -i ${genome_fna} -f gff -o ${genome_id}/${genome_id}.gff -a ${genome_id}/${genome_id}.faa -d ${genome_id}/${genome_id}.ffn`)

## Relevant logs and/or screenshots

```
INFO     : macsyfinder: L 604 :ESC[0m Searching systemsESC[0m
DEBUG    : system: L 251 :ESC[0m ##################################################ESC[0m
DEBUG    : system: L 252 :ESC[0m mandatory_genes: []ESC[0m
DEBUG    : system: L 253 :ESC[0m accessory_genes: []ESC[0m
DEBUG    : system: L 254 :ESC[0m neutral_genes: []ESC[0m
DEBUG    : system: L 255 :ESC[0m forbidden_genes: ['Tad_tadZ']ESC[0m
DEBUG    : system: L 262 :ESC[0m There is 1 forbidden genes occurrence(s): Tad_tadZESC[0m
DEBUG    : system: L 268 :ESC[0m The quorum of mandatory genes required (6) is not reached: 0ESC[0m
DEBUG    : system: L 274 :ESC[0m The quorum of genes required (9) is not reached: 0ESC[0m
Traceback (most recent call last):
  File "/miniconda3/envs/macsytest/bin/macsyfinder", line 8, in <module>
    sys.exit(main())
  File "/miniconda3/envs/macsytest/lib/python3.8/site-packages/macsypy/scripts/macsyfinder.py", line 903, in main
    all_systems, rejected_clusters = search_systems(config, model_registry, models_def_to_detect, logger)
  File "/miniconda3/envs/macsytest/lib/python3.8/site-packages/macsypy/scripts/macsyfinder.py", line 535, in search_systems
    likely_systems, rejected_hits = _search_in_unordered_replicon(hits_by_replicon, models_to_detect,
  File "/miniconda3/envs/macsytest/lib/python3.8/site-packages/macsypy/scripts/macsyfinder.py", line 608, in _search_in_unordered_replicon
    res = unordered_matcher.match(hits_related_one_model)
  File "/miniconda3/envs/macsytest/lib/python3.8/site-packages/macsypy/system.py", line 280, in match
    res = UnlikelySystem(self._model, mandatory_hits, accessory_hits, neutral_hits, forbidden_hits, reasons)
  File "/miniconda3/envs/macsytest/lib/python3.8/site-packages/macsypy/system.py", line 354, in __call__
    new_system_inst = super().__call__(*args, **kwargs)
  File "/miniconda3/envs/macsytest/lib/python3.8/site-packages/macsypy/system.py", line 830, in __init__
    super().__init__(model, mandatory_hits, accessory_hits, neutral_hits, forbidden_hits)
  File "/miniconda3/envs/macsytest/lib/python3.8/site-packages/macsypy/system.py", line 726, in __init__
    self._replicon_name = self.allowed_hits[0].replicon_name
IndexError: list index out of range
```

**Comment by cschu** [comment]
Hi @bneron, this indeed seems to work with the latest commit. Thank you very much!
