### ISSUE TITLE
Problem when running macsyfinder 2.0 for TXSS identification

### ISSUE THREAD

**Issue by zhangyumeng1sjtu** [gem-pasteur/macsyfinder#43]
Hi! I have tried to use macsyfinder 2.0 for TXSS identification, and I downloaded the model from https://github.com/macsy-models/TXSS. However, I met this problem when running the program. 
```
macsyfinder --db-type ordered_replicon --models-dir Downloads --sequence-db Downloads/test_seq.txt --models TXSS all
command used: /usr/local/anaconda3/bin/macsyfinder --db-type ordered_replicon --models-dir Downloads --sequence-db Downloads/test_seq.txt --models TXSS all
Traceback (most recent call last):
  File "/usr/local/anaconda3/bin/macsyfinder", line 8, in <module>
    sys.exit(main())
  File "/usr/local/anaconda3/lib/python3.7/site-packages/macsypy/scripts/macsyfinder.py", line 1047, in main
    relative_path=config.relative_path())
  File "/usr/local/anaconda3/lib/python3.7/site-packages/macsypy/registries.py", line 76, in scan_models_dir
    relative_path=relative_path)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/macsypy/registries.py", line 176, in __init__
    relative_path=relative_path)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/macsypy/registries.py", line 249, in _scan_profiles
    for profile in os.listdir(path):
FileNotFoundError: [Errno 2] No such file or directory: 'Downloads/Transesterase domain/profiles'
```
I have stored the models in the "Downloads" directory, and I'm confused that It said the profiles of Transesterase domain were not found.
If I use the model provided by `macsydata`, the program is running normally.
Hope for your help. Thanks!

**Comment by bneron** [comment]
in the models directory you should have only models.

**Comment by zhangyumeng1sjtu** [comment]
Thanks a lot!
