### ISSUE TITLE
how to use models

### ISSUE THREAD

**Issue by bneron** [gem-pasteur/macsyfinder#45]
Hi, 
    There are some problems with using the model. Before creating a new model, I tried the commands in the documentation as follows:
```
1.  I downloaded the original TXSS file. 
2.  macsyfinder --db-type ordered_replicon --sequence-db mygenome.fasta --models-dir TXSS --models T3SS
```
The program error is as follows:
```
Traceback (most recent call last):
  File "/home/lkj666/miniconda3/envs/macsyfinder2.0/bin/macsyfinder", line 8, in <module>
    sys.exit(main())
  File "/home/lkj666/miniconda3/envs/macsyfinder2.0/lib/python3.7/site-packages/macsypy/scripts/macsyfinder.py", line 1048, in main
    relative_path=config.relative_path())
  File "/home/lkj666/miniconda3/envs/macsyfinder2.0/lib/python3.7/site-packages/macsypy/registries.py", line 76, in scan_models_dir
    relative_path=relative_path)
  File "/home/lkj666/miniconda3/envs/macsyfinder2.0/lib/python3.7/site-packages/macsypy/registries.py", line 176, in __init__
    relative_path=relative_path)
  File "/home/lkj666/miniconda3/envs/macsyfinder2.0/lib/python3.7/site-packages/macsypy/registries.py", line 249, in _scan_profiles
    for profile in os.listdir(path):
FileNotFoundError: [Errno 2] No such file or directory: 'TXSS/definitions/profiles'
```
Then I copied the file to the appropriate directory and tried again, The program reported an error again as follows:
```
command used: /home/lkj666/miniconda3/envs/macsyfinder2.0/bin/macsyfinder --db-type ordered_replicon --sequence-db SC155.faa --models-dir TXSS --models T3SS
macsyfinder: "No such model definition: 'T3SS'"
```
Can you give me some advice? thanks

_Originally posted by @lkj66666 in https://github.com/gem-pasteur/macsyfinder/issues/34#issuecomment-1090976087_

**Comment by bneron** [comment]
If you install TXSS in canonical location (for instance in ~/.macsyfinder/models) you have not to specify --models-dir on the macsyfinder command line 

if you install TXSS in specific location it must be in a directory which contains only macsyfinder  models
and then specify this directory on the macsyfinder command line. 
But in your case it's the parents directory of TXSS directory you have to specify with the --models_dir option
