### ISSUE TITLE
[HELP] Maxyfinder fails to run

### ISSUE THREAD

**Issue by sujeetpowar** [gem-pasteur/macsyfinder#68]
Hi,

I originally wanted to run the defense-finder but had an error. So I decided to run maxyfinder to check. But still I am getting the error. I ran maxyfinder on protein sequence in gembase format generated by panacota. 

The error details are as follows:

1. The exact command lines you use  
macsyfinder  --sequence-db HEPY1402.All.prt -w 7 --db-type gembase  --models TXSS

2. Traceback (most recent call last):
  File "/home/sujeet/miniconda3/envs/defensefinder/bin/macsyfinder", line 10, in <module>
    sys.exit(main())
  File "/home/sujeet/miniconda3/envs/defensefinder/lib/python3.10/site-packages/macsypy/scripts/macsyfinder.py", line 1193, in main
    all_systems, rejected_candidates = search_systems(config, model_registry, models_def_to_detect, logger)
  File "/home/sujeet/miniconda3/envs/defensefinder/lib/python3.10/site-packages/macsypy/scripts/macsyfinder.py", line 577, in search_systems
    systems, rejected_candidates = _search_in_ordered_replicon(hits_by_replicon, models_to_detect,
  File "/home/sujeet/miniconda3/envs/defensefinder/lib/python3.10/site-packages/macsypy/scripts/macsyfinder.py", line 606, in _search_in_ordered_replicon
    rep_info = rep_db[rep_name]
  File "/home/sujeet/miniconda3/envs/defensefinder/lib/python3.10/site-packages/macsypy/database.py", line 437, in __getitem__
    return self._DB[replicon_name]
KeyError: 'HEPY.1223.00001.0001i'

***OS:*** 

 - [ ] Linux-ubuntu 22.04
 

***MacSyFinder Version:***

Macsyfinder 2.1.2

**Comment by bneron** [comment]
Unfortunately the gembase format evolved faster than MAcSyfinder, and the gembase produced by panacota is not compliant with masyfinder (https://macsyfinder.readthedocs.io/en/master/user_guide/gembase_convention.html#gembase-convention).
We will plan to adapt MacSyFinder to this new format in future releases.
